config/routes.rb
Rails.application.routes.draw do

  root 'doctors#index'
  
  resources :doctors do
    resources :appointments
  end

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :doctor
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  has_many :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @doctor = Doctor.find(params[:doctor_id])
    @appointment = Appointment.new
  end

  def create
    @doctor = Doctor.find(params[:doctor_id])
    @appointment = @doctor.appointments.create(post_params)
    if @appointment.save
      redirect_to doctor_path(@doctor)
    else
      render :new
    end
  end



  private
    def post_params
      params.require(:appointment).permit(:patient_name, :phone_number, :email, :start_time, 
                                          :end_time, :reason, :doctor_id)
    end

    def set_appointment
      @appointment = Appointment.find(params[:id])
    end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  def index
    @doctors = Doctor.all
  end

  def show
    @appointments = Appointment.where(doctor_id: params[:id]).order(:start_time)
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new(post_params)
    if @doctor.save
      redirect_to @doctor, notice: 'Doctor created successfully!'
    else
      render :new, notice: 'Unable to save new doctor'
    end
  end

  def edit
  end

  def update
    if @doctor.update(post_params)
      redirect_to @doctor, notice: 'Doctor updated successfully!'
    else
      render :edit, notice: 'Unable to update doctor'
    end
  end

  def destroy
    @doctor.destroy
    redirect_to doctors_url, notice: 'Doctor successfully deleted.'
  end



  private
    def post_params
      params.require(:doctor).permit(:name, :specialty, :description)
    end

    def set_doctor
      @doctor = Doctor.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/appointments/_form.html.erb
<%= form_for [@doctor, @appointment] do |f| %>
  <% if @appointment.errors.any? %>
  <div id='error_explanation'>
    <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited
        this appointment from being saved:
    </h2>
    <ul>
      <%= @appointment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <% end %>
  </div>
  <p>
    <%= f.label :patient_name %><br>
    <%= f.text_field :patient_name %>
  </p>
  <p>
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </p>
  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </p>

  <p>
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </p>
  <p>
    <%= f.label :reason %><br>
    <%= f.text_area :reason %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/appointments/new.html.erb
<h1>Schedule an appointment</h1>

<%= render 'form' %>

app/views/doctors/_form.html.erb
<%= form_for @doctor do |f| %>
  <% if @doctor.errors.any? %>
  <div id='error_explanation'>
    <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited
        this doctor from being saved:
    </h2>
    <ul>
      <%= @doctor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <% end %>
  </div>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :specialty %><br>
    <%= f.text_area :specialty %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/doctors/edit.html.erb
<h1>Edit Doctor <%= @doctor.name %></h1>

<%= render 'form' %>

<%= link_to 'Back', doctor_path %>

app/views/doctors/index.html.erb
<h1>Doctor Listing</h1>

<ul>
  <% @doctors.each do |doctor| %>
    <li><%= link_to doctor.name, doctor_path(doctor) %></li>
  <% end %>
</ul>

<%= link_to "Add a doctor", new_doctor_path %>

app/views/doctors/new.html.erb
<h1>Add a new doctor</h1>

<%= render 'form' %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<h1>Doctor <%= @doctor.name %></h1>

<h3><%= @doctor.specialty %></h3>
<p><%= @doctor.description %></p>

<p><strong>Appointments</strong></p>
<% @appointments.each do |appointment| %>
  <p><%= appointment.patient_name %></p>
  <ul>
    <li><%= appointment.phone_number %></li>
    <li><%= appointment.email %></li>
    <li><%= appointment.start_time %></li>
    <li><%= appointment.end_time %></li>
    <li><%= appointment.reason %></li>
  </ul>
<% end %>


<%= link_to 'Schedule an appointment', new_doctor_appointment_path(@doctor) %> | 
<%= link_to 'Back', doctors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DoctorsOffice</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>